FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# This COPY isn't needed in dev environment since we are using volumes
# and referencing directories.  However, in production, we would need
# this, so it's best to keep it.
COPY . .

CMD ["npm", "run", "start"]
